### ISSUE TITLE
Router middle wear applied even if no routes are matched

### ISSUE THREAD

**Issue by RHavar** [alexmingoia/koa-router#108]
I create a router, add some router-specific middle-ware, and then add some routes to that router.

When mounting this router in an app, the middle wear kicks, even if none of the routes are matches (only it seems, when no global routes are matched).

Here was someone's half-done patch to try fix this behavior: https://dl.dropboxusercontent.com/spa/quq37nq1583x0lf/pcwt41gt.png

**Comment by alexmingoia** [comment]
Can you provide an example of how you're mounting the router and middleware? This was a bug that was fixed in previous versions of koa-router.

**Comment by dobry-den** [comment]
Imagine we want a me.js router that ensures that a user is logged in for every route defined on that router because every route is scoped to `this.currentUser` (the logged in user):

``` javascript

////////////////////////////////////////////////////////////
// routes/me.js
////////////////////////////////////////////////////////////

var router = new require('koa-router')();

router.use(function*(next) {
  console.log('logged from /me router');
  yield next;
});

// Ensure user is logged in for all routes in this router
router.use(function*(next) {
  this.assert(this.currentUser, 403);
  yield next;
});

router.get('/me/topics', function*() {
  var topics = yield db.findTopicsForUser(this.currentUser.id);
  this.body = topics;
});

router.get('/me/subscriptions', function*() {
  var subs = yield db.findSubscriptionsForUser(this.currentUser.id);
  this.body = subs;
});

module.exports = router;

////////////////////////////////////////////////////////////
// server.js
////////////////////////////////////////////////////////////

app.use(require('./routes/me').routes());
```

That router will apply its middleware even if the request doesn't hit any of its routes:

    > curl http://localhost:3000/this-will-404
    <-- GET /this-will-404
    logged from /me router
    --> GET /this-will-404 404

I guess the real question here is: is this intentional? Perhaps I'm just misusing the library.

And the ultimate question then is: how can we define router-specific middleware?

Currently, routers always apply their middleware even if the request doesn't hit any of their routes, as seen in OP's screenshot.

**Comment by nicholaswyoung** [comment]
@dobry-den Have you tried mounting the router at ```/me``` using [koa-mount](https://github.com/koajs/mount)? That might help.

**Comment by alexmingoia** [comment]
This is intentional but counter-intuitive. `Router.use(middleware)` is essentially sugar for `compose([middleware, router.routes()])`. I agree it would be intuitive to have `Router.use()` only run given middleware if it matches one of that router's routes.

**Comment by dobry-den** [comment]
@nicholaswyoung Yes, but I found that mounting is most useful when you're mounting to some `/segment` that your router doesn't care about. A good example of this is `/v1`, `/v2`, etc. segments for your API so that you can write versioned routers that don't need to know which version they are.

For a segment that doesn't change, like my `/me` example, I found that mounting doesn't offer anything since your router *does* need to distinguish between `/me/things` (an endpoint scoped to the current user) vs `/things` (a public endpoint). In other words, I found that when I'm writing a router under the assumption that it will be mounted to a specific segment, then I probably should reconsider whether I should be mounting the router at all.

Perhaps hard to explain without examples. Like you guys, I'm still experimenting and trying to arrive at the best and most general patterns for my Koa apps.

@alexmingoia Thanks for being open to the idea. I only have brief experience with Express4, but I found its router to be intuitive while allowing behavior that I describe. Sounds like koa-router 5.0.0 will be Koa's answer to the problem.

Killer work, man. I'm glad the Koa ecosystem has people like you and your project's contributors.

**Comment by alexmingoia** [comment]
I'm very sorry for the miscommunication but I forgot this was already fixed. 4.2.0 and above only apply router middleware if a route matches, as it should.
