### ISSUE TITLE
middleware without path doesn't work

### ISSUE THREAD

**Issue by letchik** [alexmingoia/koa-router#161]
I have a simple code
```
let router = new Router();
router.get('/',
  function *(next) {
    ...
  }
);
router.use(
  function *(next) {
    console.log('middleware');
    ...
    yield next;
  }
);
```
it doesn't work in this case, middlware didn't call
the other way works fine
```
router.use('/',
  function *(next) {
    console.log('middleware');
    ...
    yield next;
  }
);
```

**Comment by divmgl** [comment]
This is happening to me as well. Interesting bug. Is this relatively new?

**Comment by divmgl** [comment]
It's actually not working for me whatsoever.

```
var router = new Router();

router.use("/", function * (next) {
  console.log('Route hit');
  yield next;
});

app.use(router.routes());
```

Getting a 404 error... Not sure what's going on. Tried looking in the `libs/router.js` to find the bug but everything seems to be working correctly.

**Comment by divmgl** [comment]
I already figured out the problem... I cannot fathom why this is designed this way, but this is the solution that's working for me.

In `Route.prototype.routes`, it is currently ignoring middleware that has no URL.

```
var path = router.opts.routerPath || this.routerPath || this.path;
var matched = router.match(path, this.method);
// ...
if (matched.route) {
  // middleware code...
}
```

It properly finds the middleware and matches it, but because it has no route, it doesn't add it to the middleware stack. Here's some ugly code I put in to make it work.

```
if (matched.route) {
      console.log(matched.route);

      this.route = matched.route;
      this.captures = this.route.captures(path, this.captures);
      this.params = this.route.params(path, this.captures, this.params);

      debug('dispatch %s %s', this.route.path, this.route.regexp);

      next = matched.route.middleware.call(this, next);

      for (var i = 0, l = matched.middleware.length; i < l; i++) {
        next = matched.middleware[i].call(this, next);
      }
    }
    // THIS IS WHERE MY CODE STARTS
    else if (matched) {
      for (var i = 0, l = matched.middleware.length; i < l; i++) {
        next = matched.middleware[i].call(this, next);
      }
    }
```

Now all `router.use` commands with no URL are getting invoked on every request. Again, I don't understand why this is happening and this is by no means a permanent solution.

**Comment by divmgl** [comment]
I improved this code further.

```
if (matched.route) {
  this.route = matched.route;
  this.captures = this.route.captures(path, this.captures);
  this.params = this.route.params(path, this.captures, this.params);

  debug('dispatch %s %s', this.route.path, this.route.regexp);

  next = matched.route.middleware.call(this, next);
} else if (matched.middleware) {
  for (var i = 0, l = matched.middleware.length; i < l; i++) {
    next = matched.middleware[i].call(this, next);
  }
}
```

I need to run tests and make sure everything's working however. Until I do that I won't be opening a pull request.

**Comment by divmgl** [comment]
I've been looking into this issue a little further (seeing as @alexmingoia has not yet merged the pull request), and unfortunately `use` statements without URLs will only get called when a route is matched.

```
  router.use(function * (next) {
    console.log('"use" is called');
    yield next;
  });

  router.all('/', function * (next) {
    console.log('"all" is called');
    yield next;
  })

// Output:
// "use" is called
// "all" is called
```

This will make it so that `use` statements without URLs will get called regardless of having a route supplied. This allows for configurations where having routes registered through `koa-router` isn't necessary because other middleware takes care of it, like this:

```
var serve = require('koa-static');
var router = new (require('koa-router')());

router.use(serve('/../public'));

[
  '/customer',
  '/customer/:id'
].forEach(function(route){
  router.use(rewrite(route, "/"));
});

app.use(router.middleware());
app.listen(80);
```

Would be nice to have this in the master branch.

**Comment by divmgl** [comment]
@letchik your code is working in the master branch. You may be something wrong in your setup.
