### ISSUE TITLE
route.use, path not being recongized

### ISSUE THREAD

**Issue by uptownhr** [alexmingoia/koa-router#190]
```
router.prefix('/admin')

  router.use('/', function *(next){
    console.log('test','wtf')
    this.body = 'wtf'
  })
```
The above triggers when going to /admin. However when `router.use('/anythingelse')` the path will not match. Any reason?

**Comment by alexmingoia** [comment]
That's that's the intended behavior, if I understand you correctly. If you prefix a router with a path, "/admin", it's middleware will only run if the requested URL begins with that path. That's the purpose of it.

If you want to run middleware at any path, mount it using `app.use()` instead. That way, it will run regardless of the requested URL.

**Comment by uptownhr** [comment]
hmm interesting. since router.get works without specifying the entire path, I assumed router.use would follow the behaviour when prefix is set.

**Comment by naxmefy** [comment]
i think this problem isnt solved...

because i got this problem:

```JavaScript
router.use('/assets', bla.assetHandler);
```

Now i want that any call to e.g.

* /assets/asset.js
* /assets/asset.css
* /assets/asset.png

and whatever - should trigger the ``` assetHandler ``` because the handler will do some task like compiling or whatever

with "app.use" it works, but for every route is calling, he try to find a asset also for

* /admin
* /my-custom-landing-page

in this case every time the assethandler checks all asset folder for ``` /admin ``` asset - but is not needed...

and

```JavaScript
router.use('/assets', bla.assetHandler);
```
wont work because no get, post or whatever is defined...

> expected behavior should like the default expressjs routing or not?
