### ISSUE TITLE
Passing param to router.redirect()

### ISSUE THREAD

**Issue by sk25649** [alexmingoia/koa-router#289]
Hi,

is it possible to pass param using `router.redirect(source, destination)`?

**Comment by chrisnicola** [comment]
router.redirect is just a shortcut to a function that redirects directly to `destination` as a string. Params would not be useful since `destination` isn't a function.

The only thing redirect does other than redirect is set the status code to 301 by default. You are better just handling it with `get` or `all`. That said I suppose it might make logical sense to support the case where `destination` is a function and still keep the convenience of setting the status code automatically.

If there is interest in this I'd be willing to submit a PR.

**Comment by jbielick** [comment]
Do you mean URL params (querystring)? Any URL can be passed in for `destination` so you could use the `querystring` module to turn some object into a querystring and append that to your URL if you wanted. Please reopen if that does not resolve your issue.

**Comment by chrisnicola** [comment]
@jbielick I think he's thinking something more like:

```
router.redirect('/path/:id', (ctx) => {
  return `/new-path/${ctx.params.id}`
})
```

In other words, instead of a static redirect, the redirect path could be dynamic and work with path parameters. I may be mistaken but I think this makes sense.

So the proposal is to change `redirect` so that it can support both a static string and a dynamic handler function that returns a url string to redirect to.
