### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Fjandin** [alexmingoia/koa-router#414]
Started using koa and koa-router and have some questions if you don't mind :) 

1. When i add a prefix to a router for example `/rest/v1` and add some route for example `/users/:userId` the end result is `/rest/v1(.*)/users/:userId` and specific reason for the `.*` ?

2. The end result `ctx.params` end up beeing for example `{"0":"", "userId": "1"}`. Why the `0` key?

3. Would it not make sense to put `params` in the request object, just like query, headers etc.. and make an alias on the ctx root?

Maybe i'm just misunderstanding something :P As i said. Just started using koa

**Comment by jbielick** [comment]
Hi there.
Let me see if I can answer these...

1. This is a bug and has been fixed in 7.4.0, see #423 Thanks for asking.

2. I'm really not sure where that's coming from. It was addressed a little bit here: https://github.com/alexmingoia/koa-router/pull/287 Could you provide a simple example case of how/when it appears in your code?

3. `koa-router` does not own the `Request` object and appending to it has the possibility of clashing or conforming to its API. To be unobtrusive and follow `koa`'s recommendation about where to place data shared amongst middleware and the request lifecycle, we use `ctx` to store a reference to the URL params as it has nothing to do with the HTTP request itself, but the interpretation of the request path by this library and user code.
