### ISSUE TITLE
Route parameters in array

### ISSUE THREAD

**Issue by amsul** [alexmingoia/koa-router#87]
I apologize for my naiveté if this is a noob question, but is there a reason why `this.params` is an array instead of an object?

Seems like the only way to deal with it is as an object (it’s internally treated as such as well)... So why not just make it one?

It’s currently a bit annoying say, for example, when I stringify the params for logging, the keys and values don’t show up:

```js
JSON.stringify(this.params) // []
```

Instead I have to do this:

```js
function arrayToObject(array) {
  return Object.keys(array).reduce(function(o, key) {
    o[key] = array[key]
    return o
  }, {})
}
JSON.stringify(arrayToObject(this.params))
```

**Comment by garrett-gottlieb** [comment]
+1

**Comment by nuarhu** [comment]
Furthermore, this Array is not usable other than accessing directly the properties.

It cannot be iterated because it is an Array (e.g. lodash returns true for _.isArray()) but it always has a length of 0.

Example:

    // supposed that this is the case
    this.params === [ account: 'me123' ]
    // then
    _.isArray(this.params) === true
    // and at the same time
    this.params.length === 0

Which means that calling map() or forEach() on this.params does not work. I have yet to find a way how to access what is stored in this "Array" whithout knowledge of the specific parameters.

(I stumbled over this because I'm trying to implement a generic white filter.)

**Comment by alexmingoia** [comment]
The new `4.0.0` release separates these two into `ctx.params` (map of named params) and `ctx.captures` (array of regexp captures) respectively.

**Comment by garrett-gottlieb** [comment]
Awesome! Thanks, @alexmingoia.
